<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContainerProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $container_product = [
            [
                'demand_id' => '25',
                'shipping_id' => '1',
                'quantity' => '2457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '2',
                'quantity' => '2116',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '1',
                'quantity' => '105',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '7',
                'shipping_id' => '1',
                'quantity' => '483',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '13',
                'shipping_id' => '1',
                'quantity' => '2288',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '1',
                'quantity' => '450',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '18',
                'shipping_id' => '1',
                'quantity' => '2420',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '15',
                'shipping_id' => '1',
                'quantity' => '371',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '24',
                'shipping_id' => '1',
                'quantity' => '3103',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '19',
                'shipping_id' => '1',
                'quantity' => '542',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '2',
                'quantity' => '1939',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '1',
                'shipping_id' => '1',
                'quantity' => '2384',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '16',
                'shipping_id' => '1',
                'quantity' => '724',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '4',
                'shipping_id' => '1',
                'quantity' => '205',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '1',
                'quantity' => '866',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '8',
                'shipping_id' => '1',
                'quantity' => '353',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '9',
                'shipping_id' => '1',
                'quantity' => '2108',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '10',
                'shipping_id' => '1',
                'quantity' => '728',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '6',
                'shipping_id' => '1',
                'quantity' => '2783',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '22',
                'shipping_id' => '1',
                'quantity' => '457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '2',
                'quantity' => '593',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '2',
                'quantity' => '2709',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '11',
                'shipping_id' => '1',
                'quantity' => '465',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '12',
                'shipping_id' => '1',
                'quantity' => '2828',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '5',
                'shipping_id' => '1',
                'quantity' => '788',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '38',
                'quantity' => '2457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '39',
                'quantity' => '2116',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '38',
                'quantity' => '105',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '7',
                'shipping_id' => '38',
                'quantity' => '483',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '13',
                'shipping_id' => '38',
                'quantity' => '2288',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '38',
                'quantity' => '450',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '18',
                'shipping_id' => '38',
                'quantity' => '2420',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '15',
                'shipping_id' => '38',
                'quantity' => '371',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '24',
                'shipping_id' => '38',
                'quantity' => '3103',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '19',
                'shipping_id' => '38',
                'quantity' => '542',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '39',
                'quantity' => '1939',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '1',
                'shipping_id' => '38',
                'quantity' => '2384',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '16',
                'shipping_id' => '38',
                'quantity' => '724',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '4',
                'shipping_id' => '38',
                'quantity' => '205',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '38',
                'quantity' => '866',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '8',
                'shipping_id' => '38',
                'quantity' => '353',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '9',
                'shipping_id' => '38',
                'quantity' => '2108',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '10',
                'shipping_id' => '38',
                'quantity' => '728',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '6',
                'shipping_id' => '38',
                'quantity' => '2783',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '22',
                'shipping_id' => '38',
                'quantity' => '457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '39',
                'quantity' => '593',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '39',
                'quantity' => '2709',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '11',
                'shipping_id' => '38',
                'quantity' => '465',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '12',
                'shipping_id' => '38',
                'quantity' => '2828',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '5',
                'shipping_id' => '38',
                'quantity' => '788',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '75',
                'quantity' => '2457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '76',
                'quantity' => '2116',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '75',
                'quantity' => '105',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '7',
                'shipping_id' => '75',
                'quantity' => '483',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '13',
                'shipping_id' => '75',
                'quantity' => '2288',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '75',
                'quantity' => '450',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '18',
                'shipping_id' => '75',
                'quantity' => '2420',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '15',
                'shipping_id' => '75',
                'quantity' => '371',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '24',
                'shipping_id' => '75',
                'quantity' => '3103',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '19',
                'shipping_id' => '75',
                'quantity' => '542',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '76',
                'quantity' => '1939',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '1',
                'shipping_id' => '75',
                'quantity' => '2384',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '16',
                'shipping_id' => '75',
                'quantity' => '724',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '4',
                'shipping_id' => '75',
                'quantity' => '205',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '75',
                'quantity' => '866',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '8',
                'shipping_id' => '75',
                'quantity' => '353',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '9',
                'shipping_id' => '75',
                'quantity' => '2108',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '10',
                'shipping_id' => '75',
                'quantity' => '728',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '6',
                'shipping_id' => '75',
                'quantity' => '2783',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '22',
                'shipping_id' => '75',
                'quantity' => '457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '76',
                'quantity' => '593',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '76',
                'quantity' => '2709',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '11',
                'shipping_id' => '75',
                'quantity' => '465',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '12',
                'shipping_id' => '75',
                'quantity' => '2828',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '5',
                'shipping_id' => '75',
                'quantity' => '788',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '112',
                'quantity' => '2457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '113',
                'quantity' => '2116',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '112',
                'quantity' => '105',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '7',
                'shipping_id' => '112',
                'quantity' => '483',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '13',
                'shipping_id' => '112',
                'quantity' => '2288',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '112',
                'quantity' => '450',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '18',
                'shipping_id' => '112',
                'quantity' => '2420',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '15',
                'shipping_id' => '112',
                'quantity' => '371',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '24',
                'shipping_id' => '112',
                'quantity' => '3103',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '19',
                'shipping_id' => '112',
                'quantity' => '542',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '113',
                'quantity' => '1939',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '1',
                'shipping_id' => '112',
                'quantity' => '2384',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '16',
                'shipping_id' => '112',
                'quantity' => '724',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '4',
                'shipping_id' => '112',
                'quantity' => '205',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '112',
                'quantity' => '866',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '8',
                'shipping_id' => '112',
                'quantity' => '353',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '9',
                'shipping_id' => '112',
                'quantity' => '2108',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '10',
                'shipping_id' => '112',
                'quantity' => '728',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '6',
                'shipping_id' => '112',
                'quantity' => '2783',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '22',
                'shipping_id' => '112',
                'quantity' => '457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '113',
                'quantity' => '593',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '113',
                'quantity' => '2709',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '11',
                'shipping_id' => '112',
                'quantity' => '465',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '12',
                'shipping_id' => '112',
                'quantity' => '2828',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '5',
                'shipping_id' => '112',
                'quantity' => '788',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '149',
                'quantity' => '2457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '150',
                'quantity' => '2116',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '149',
                'quantity' => '105',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '7',
                'shipping_id' => '149',
                'quantity' => '483',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '13',
                'shipping_id' => '149',
                'quantity' => '2288',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '149',
                'quantity' => '450',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '18',
                'shipping_id' => '149',
                'quantity' => '2420',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '15',
                'shipping_id' => '149',
                'quantity' => '371',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '24',
                'shipping_id' => '149',
                'quantity' => '3103',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '19',
                'shipping_id' => '149',
                'quantity' => '542',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '150',
                'quantity' => '1939',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '1',
                'shipping_id' => '149',
                'quantity' => '2384',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '16',
                'shipping_id' => '149',
                'quantity' => '724',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '4',
                'shipping_id' => '149',
                'quantity' => '205',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '149',
                'quantity' => '866',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '8',
                'shipping_id' => '149',
                'quantity' => '353',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '9',
                'shipping_id' => '149',
                'quantity' => '2108',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '10',
                'shipping_id' => '149',
                'quantity' => '728',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '6',
                'shipping_id' => '149',
                'quantity' => '2783',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '22',
                'shipping_id' => '149',
                'quantity' => '457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '150',
                'quantity' => '593',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '150',
                'quantity' => '2709',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '11',
                'shipping_id' => '149',
                'quantity' => '465',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '12',
                'shipping_id' => '149',
                'quantity' => '2828',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '5',
                'shipping_id' => '149',
                'quantity' => '788',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '186',
                'quantity' => '2457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '187',
                'quantity' => '2116',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '186',
                'quantity' => '105',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '7',
                'shipping_id' => '186',
                'quantity' => '483',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '13',
                'shipping_id' => '186',
                'quantity' => '2288',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '186',
                'quantity' => '450',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '18',
                'shipping_id' => '186',
                'quantity' => '2420',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '15',
                'shipping_id' => '186',
                'quantity' => '371',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '24',
                'shipping_id' => '186',
                'quantity' => '3103',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '19',
                'shipping_id' => '186',
                'quantity' => '542',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '187',
                'quantity' => '1939',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '1',
                'shipping_id' => '186',
                'quantity' => '2384',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '16',
                'shipping_id' => '186',
                'quantity' => '724',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '4',
                'shipping_id' => '186',
                'quantity' => '205',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '186',
                'quantity' => '866',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '8',
                'shipping_id' => '186',
                'quantity' => '353',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '9',
                'shipping_id' => '186',
                'quantity' => '2108',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '10',
                'shipping_id' => '186',
                'quantity' => '728',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '6',
                'shipping_id' => '186',
                'quantity' => '2783',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '22',
                'shipping_id' => '186',
                'quantity' => '457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '187',
                'quantity' => '593',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '187',
                'quantity' => '2709',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '11',
                'shipping_id' => '186',
                'quantity' => '465',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '12',
                'shipping_id' => '186',
                'quantity' => '2828',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '5',
                'shipping_id' => '186',
                'quantity' => '788',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '223',
                'quantity' => '2457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '224',
                'quantity' => '2116',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '223',
                'quantity' => '105',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '7',
                'shipping_id' => '223',
                'quantity' => '483',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '13',
                'shipping_id' => '223',
                'quantity' => '2288',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '223',
                'quantity' => '450',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '18',
                'shipping_id' => '223',
                'quantity' => '2420',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '15',
                'shipping_id' => '223',
                'quantity' => '371',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '24',
                'shipping_id' => '223',
                'quantity' => '3103',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '19',
                'shipping_id' => '223',
                'quantity' => '542',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '224',
                'quantity' => '1939',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '1',
                'shipping_id' => '223',
                'quantity' => '2384',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '16',
                'shipping_id' => '223',
                'quantity' => '724',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '4',
                'shipping_id' => '223',
                'quantity' => '205',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '223',
                'quantity' => '866',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '8',
                'shipping_id' => '223',
                'quantity' => '353',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '9',
                'shipping_id' => '223',
                'quantity' => '2108',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '10',
                'shipping_id' => '223',
                'quantity' => '728',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '6',
                'shipping_id' => '223',
                'quantity' => '2783',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '22',
                'shipping_id' => '223',
                'quantity' => '457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '224',
                'quantity' => '593',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '224',
                'quantity' => '2709',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '11',
                'shipping_id' => '223',
                'quantity' => '465',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '12',
                'shipping_id' => '223',
                'quantity' => '2828',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '5',
                'shipping_id' => '223',
                'quantity' => '788',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '260',
                'quantity' => '2457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '261',
                'quantity' => '2116',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '260',
                'quantity' => '105',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '7',
                'shipping_id' => '260',
                'quantity' => '483',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '13',
                'shipping_id' => '260',
                'quantity' => '2288',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '260',
                'quantity' => '450',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '18',
                'shipping_id' => '260',
                'quantity' => '2420',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '15',
                'shipping_id' => '260',
                'quantity' => '371',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '24',
                'shipping_id' => '260',
                'quantity' => '3103',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '19',
                'shipping_id' => '260',
                'quantity' => '542',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '261',
                'quantity' => '1939',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '1',
                'shipping_id' => '260',
                'quantity' => '2384',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '16',
                'shipping_id' => '260',
                'quantity' => '724',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '4',
                'shipping_id' => '260',
                'quantity' => '205',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '260',
                'quantity' => '866',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '8',
                'shipping_id' => '260',
                'quantity' => '353',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '9',
                'shipping_id' => '260',
                'quantity' => '2108',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '10',
                'shipping_id' => '260',
                'quantity' => '728',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '6',
                'shipping_id' => '260',
                'quantity' => '2783',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '22',
                'shipping_id' => '260',
                'quantity' => '457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '261',
                'quantity' => '593',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '261',
                'quantity' => '2709',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '11',
                'shipping_id' => '260',
                'quantity' => '465',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '12',
                'shipping_id' => '260',
                'quantity' => '2828',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '5',
                'shipping_id' => '260',
                'quantity' => '788',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '297',
                'quantity' => '2457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '298',
                'quantity' => '2116',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '297',
                'quantity' => '105',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '7',
                'shipping_id' => '297',
                'quantity' => '483',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '13',
                'shipping_id' => '297',
                'quantity' => '2288',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '297',
                'quantity' => '450',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '18',
                'shipping_id' => '297',
                'quantity' => '2420',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '15',
                'shipping_id' => '297',
                'quantity' => '371',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '24',
                'shipping_id' => '297',
                'quantity' => '3103',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '19',
                'shipping_id' => '297',
                'quantity' => '542',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '298',
                'quantity' => '1939',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '1',
                'shipping_id' => '297',
                'quantity' => '2384',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '16',
                'shipping_id' => '297',
                'quantity' => '724',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '4',
                'shipping_id' => '297',
                'quantity' => '205',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '297',
                'quantity' => '866',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '8',
                'shipping_id' => '297',
                'quantity' => '353',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '9',
                'shipping_id' => '297',
                'quantity' => '2108',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '10',
                'shipping_id' => '297',
                'quantity' => '728',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '6',
                'shipping_id' => '297',
                'quantity' => '2783',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '22',
                'shipping_id' => '297',
                'quantity' => '457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '298',
                'quantity' => '593',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '298',
                'quantity' => '2709',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '11',
                'shipping_id' => '297',
                'quantity' => '465',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '12',
                'shipping_id' => '297',
                'quantity' => '2828',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '5',
                'shipping_id' => '297',
                'quantity' => '788',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '334',
                'quantity' => '2457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '25',
                'shipping_id' => '335',
                'quantity' => '2116',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '334',
                'quantity' => '105',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '7',
                'shipping_id' => '334',
                'quantity' => '483',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '13',
                'shipping_id' => '334',
                'quantity' => '2288',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '334',
                'quantity' => '450',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '18',
                'shipping_id' => '334',
                'quantity' => '2420',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '15',
                'shipping_id' => '334',
                'quantity' => '371',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '24',
                'shipping_id' => '334',
                'quantity' => '3103',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '19',
                'shipping_id' => '334',
                'quantity' => '542',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '14',
                'shipping_id' => '335',
                'quantity' => '1939',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '1',
                'shipping_id' => '334',
                'quantity' => '2384',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '16',
                'shipping_id' => '334',
                'quantity' => '724',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '4',
                'shipping_id' => '334',
                'quantity' => '205',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '334',
                'quantity' => '866',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '8',
                'shipping_id' => '334',
                'quantity' => '353',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '9',
                'shipping_id' => '334',
                'quantity' => '2108',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '10',
                'shipping_id' => '334',
                'quantity' => '728',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '6',
                'shipping_id' => '334',
                'quantity' => '2783',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '22',
                'shipping_id' => '334',
                'quantity' => '457',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '21',
                'shipping_id' => '335',
                'quantity' => '593',
                'answer_key' => 'reject',
            ],
            [
                'demand_id' => '20',
                'shipping_id' => '335',
                'quantity' => '2709',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '11',
                'shipping_id' => '334',
                'quantity' => '465',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '12',
                'shipping_id' => '334',
                'quantity' => '2828',
                'answer_key' => 'accepted',
            ],
            [
                'demand_id' => '5',
                'shipping_id' => '334',
                'quantity' => '788',
                'answer_key' => 'reject',
            ],
        ];
        DB::table('container_product')->insert($container_product);
    }
}
