<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $demand = [
        //     [
        //         'name' => 'Daging',
        //         'volume' => '0.61',
        //         'quantity' => '32',
        //         'weight' => '2',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Sayur',
        //         'volume' => '0.91',
        //         'quantity' => '39',
        //         'weight' => '4',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Susu Kotak',
        //         'volume' => '0.47',
        //         'quantity' => '40',
        //         'weight' => '1',
        //         'ship_date' => '2023-08-01',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Cangkul',
        //         'volume' => '0.24',
        //         'quantity' => '9',
        //         'weight' => '2',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Bed Frame',
        //         'volume' => '2.00',
        //         'quantity' => '12',
        //         'weight' => '80',
        //         'ship_date' => '2023-08-04',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Palu',
        //         'volume' => '0.41',
        //         'quantity' => '11',
        //         'weight' => '2',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Balok Baja',
        //         'volume' => '0.21',
        //         'quantity' => '69',
        //         'weight' => '405',
        //         'ship_date' => '2023-08-05',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Sekop',
        //         'volume' => '2.44',
        //         'quantity' => '17',
        //         'weight' => '3',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Buah-buahan',
        //         'volume' => '0.91',
        //         'quantity' => '45',
        //         'weight' => '1',
        //         'ship_date' => '2023-08-01',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Smartphone(s)',
        //         'volume' => '1.22',
        //         'quantity' => '20',
        //         'weight' => '0.14',
        //         'ship_date' => '2023-08-01',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Minuman Alkohol',
        //         'volume' => '0.91',
        //         'quantity' => '12',
        //         'weight' => '3',
        //         'ship_date' => '2023-08-01',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Bijih Kopi',
        //         'volume' => '1.13',
        //         'quantity' => '23',
        //         'weight' => '50',
        //         'ship_date' => '2023-08-05',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Motor',
        //         'volume' => '8.10',
        //         'quantity' => '7',
        //         'weight' => '149',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Susu Kotak',
        //         'volume' => '1.53',
        //         'quantity' => '21',
        //         'weight' => '1',
        //         'ship_date' => '2023-08-01',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Laptop(s)',
        //         'volume' => '0.61',
        //         'quantity' => '15',
        //         'weight' => '3',
        //         'ship_date' => '2023-08-01',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'TV',
        //         'volume' => '0.94',
        //         'quantity' => '28',
        //         'weight' => '9',
        //         'ship_date' => '2023-08-05',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Bunga',
        //         'volume' => '4.00',
        //         'quantity' => '3',
        //         'weight' => '2',
        //         'ship_date' => '2023-08-04',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Tangga Lipat',
        //         'volume' => '1.50',
        //         'quantity' => '4',
        //         'weight' => '2',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Beton',
        //         'volume' => '8.14',
        //         'quantity' => '7',
        //         'weight' => '20',
        //         'ship_date' => '2023-08-04',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Buah-buahan',
        //         'volume' => '0.91',
        //         'quantity' => '12',
        //         'weight' => '1',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Bata',
        //         'volume' => '7.12',
        //         'quantity' => '10',
        //         'weight' => '20',
        //         'ship_date' => '2023-08-05',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Sepeda',
        //         'volume' => '2.16',
        //         'quantity' => '2',
        //         'weight' => '20',
        //         'ship_date' => '2023-08-04',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Sofa',
        //         'volume' => '2.10',
        //         'quantity' => '15',
        //         'weight' => '66',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Paku',
        //         'volume' => '0.06',
        //         'quantity' => '89',
        //         'weight' => '1',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Sofa',
        //         'volume' => '1.93',
        //         'quantity' => '15',
        //         'weight' => '66',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Oli',
        //         'volume' => '21000',
        //         'quantity' => '2',
        //         'weight' => '16590',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'LPG',
        //         'volume' => '22587',
        //         'quantity' => '3',
        //         'weight' => '11519',
        //         'ship_date' => '2023-08-01',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Hidrogen Perokside',
        //         'volume' => '25707',
        //         'quantity' => '2',
        //         'weight' => '12853',
        //         'ship_date' => '2023-08-05',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Bensin',
        //         'volume' => '18537',
        //         'quantity' => '3',
        //         'weight' => '16030',
        //         'ship_date' => '2023-08-02',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Acetone',
        //         'volume' => '20650',
        //         'quantity' => '3',
        //         'weight' => '16210',
        //         'ship_date' => '2023-08-04',
        //         'period_id' => '1',
        //     ],
        //     [
        //         'name' => 'Bensin',
        //         'volume' => '18537',
        //         'quantity' => '2',
        //         'weight' => '16030',
        //         'ship_date' => '2023-08-04',
        //         'period_id' => '1',
        //     ],
        // ];
        // DB::table('demands')->insert($demand);
    }
}
