<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $demand = [
            [
                'name' => 'Daging',
                'volume' => '0.61',
                'quantity' => '32',
                'weight' => '2',
                'city' => 'Thailand',
                'container' => 'Refrigerated Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Kangkung',
                'volume' => '0.91',
                'quantity' => '39',
                'weight' => '4',
                'city' => 'Thailand',
                'container' => 'Refrigerated Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Susu Kotak',
                'volume' => '0.87',
                'quantity' => '40',
                'weight' => '1',
                'city' => 'Malaysia',
                'container' => 'Refrigerated Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Cangkul',
                'volume' => '0.24',
                'quantity' => '9',
                'weight' => '2',
                'city' => 'Thailand',
                'container' => 'General Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Bed Frame',
                'volume' => '2.00',
                'quantity' => '12',
                'weight' => '80',
                'city' => 'Vietnam',
                'container' => 'Fantainer/Ventilation',
                'period_id' => '1',
            ],
            [
                'name' => 'Palu',
                'volume' => '0.41',
                'quantity' => '11',
                'weight' => '2',
                'city' => 'Thailand',
                'container' => 'General Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Balok Baja',
                'volume' => '0.41',
                'quantity' => '69',
                'weight' => '405',
                'city' => 'Philippines',
                'container' => 'General Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Sekop',
                'volume' => '2.44',
                'quantity' => '17',
                'weight' => '3',
                'city' => 'Thailand',
                'container' => 'General Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Wortel',
                'volume' => '0.91',
                'quantity' => '45',
                'weight' => '1',
                'city' => 'Thailand',
                'container' => 'Refrigerated Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Smartphone(s)',
                'volume' => '1.22',
                'quantity' => '16',
                'weight' => '0.14',
                'city' => 'Malaysia',
                'container' => 'Fantainer/Ventilation',
                'period_id' => '1',
            ],
            [
                'name' => 'Minuman Alcohol',
                'volume' => '0.91',
                'quantity' => '12',
                'weight' => '3',
                'city' => 'Malaysia',
                'container' => 'Refrigerated Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Bijih Kopi',
                'volume' => '1.13',
                'quantity' => '23',
                'weight' => '50',
                'city' => 'Philippines',
                'container' => 'Fantainer/Ventilation',
                'period_id' => '1',
            ],
            [
                'name' => 'Motor',
                'volume' => '8.10',
                'quantity' => '7',
                'weight' => '149',
                'city' => 'Thailand',
                'container' => 'General Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Susu Kotak',
                'volume' => '1.53',
                'quantity' => '15',
                'weight' => '1',
                'city' => 'Malaysia',
                'container' => 'Refrigerated Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Laptop(s)',
                'volume' => '0.61',
                'quantity' => '15',
                'weight' => '3',
                'city' => 'Malaysia',
                'container' => 'Fantainer/Ventilation',
                'period_id' => '1',
            ],
            [
                'name' => 'TV',
                'volume' => '0.94',
                'quantity' => '28',
                'weight' => '9',
                'city' => 'Philippines',
                'container' => 'Fantainer/Ventilation',
                'period_id' => '1',
            ],
            [
                'name' => 'Meja',
                'volume' => '4.00',
                'quantity' => '7',
                'weight' => '8',
                'city' => 'Vietnam',
                'container' => 'General Container/Fantainer/Ventilation',
                'period_id' => '1',
            ],
            [
                'name' => 'Tangga Lipat',
                'volume' => '1.50',
                'quantity' => '4',
                'weight' => '2',
                'city' => 'Thailand',
                'container' => 'General Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Beton',
                'volume' => '8.14',
                'quantity' => '7',
                'weight' => '20',
                'city' => 'Vietnam',
                'container' => 'General Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Apel',
                'volume' => '0.91',
                'quantity' => '12',
                'weight' => '1',
                'city' => 'Thailand',
                'container' => 'Refrigerated Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Bata',
                'volume' => '7.12',
                'quantity' => '10',
                'weight' => '20',
                'city' => 'Philippines',
                'container' => 'General Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Sepeda',
                'volume' => '2.16',
                'quantity' => '12',
                'weight' => '20',
                'city' => 'Vietnam',
                'container' => 'General Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Sofa',
                'volume' => '2.10',
                'quantity' => '23',
                'weight' => '66',
                'city' => 'Thailand',
                'container' => 'Fantainer/Ventilation',
                'period_id' => '1',
            ],
            [
                'name' => 'Paku',
                'volume' => '0.06',
                'quantity' => '89',
                'weight' => '1',
                'city' => 'Thailand',
                'container' => 'General Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Sofa',
                'volume' => '1.93',
                'quantity' => '15',
                'weight' => '66',
                'city' => 'Thailand',
                'container' => 'Fantainer/Ventilation',
                'period_id' => '1',
            ],
            [
                'name' => 'Oli',
                'volume' => '21000',
                'quantity' => '2',
                'weight' => '16590',
                'city' => 'Thailand',
                'container' => 'Tank Container',
                'period_id' => '1',
            ],
            [
                'name' => 'LPG',
                'volume' => '22587',
                'quantity' => '3',
                'weight' => '11519',
                'city' => 'Malaysia',
                'container' => 'Tank Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Hidrogen Peroksida',
                'volume' => '25707',
                'quantity' => '2',
                'weight' => '12853',
                'city' => 'Philippines',
                'container' => 'Tank Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Bensin',
                'volume' => '18537',
                'quantity' => '3',
                'weight' => '16030',
                'city' => 'Thailand',
                'container' => 'Tank Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Acetone',
                'volume' => '20650',
                'quantity' => '3',
                'weight' => '16210',
                'city' => 'Vietnam',
                'container' => 'Tank Container',
                'period_id' => '1',
            ],
            [
                'name' => 'Bensin',
                'volume' => '18537',
                'quantity' => '2',
                'weight' => '16030',
                'city' => 'Vietnam',
                'container' => 'Tank Container',
                'period_id' => '1',
            ],
        ];
        DB::table('demands')->insert($demand);
    }
}
