<?php

use Illuminate\Database\Seeder;

class DemandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $demand = [
            [
                'id' => '1',
                'name' => 'Daging',
                'volume' => '0.61',
                'jumlah' => '32',
                'bobot' => '2',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '2',
                'name' => 'Sayur',
                'volume' => '0.91',
                'jumlah' => '39',
                'bobot' => '4',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '3',
                'name' => 'Susu Kotak',
                'volume' => '0.47',
                'jumlah' => '40',
                'bobot' => '1',
                'tgl_pengiriman' => '2023-08-01',
            ],
            [
                'id' => '4',
                'name' => 'Cangkul',
                'volume' => '0.24',
                'jumlah' => '9',
                'bobot' => '2',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '5',
                'name' => 'Bed Frame',
                'volume' => '2.00',
                'jumlah' => '12',
                'bobot' => '80',
                'tgl_pengiriman' => '2023-08-04',
            ],
            [
                'id' => '6',
                'name' => 'Palu',
                'volume' => '0.41',
                'jumlah' => '11',
                'bobot' => '2',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '7',
                'name' => 'Balok Baja',
                'volume' => '0.21',
                'jumlah' => '69',
                'bobot' => '405',
                'tgl_pengiriman' => '2023-08-05',
            ],
            [
                'id' => '8',
                'name' => 'Sekop',
                'volume' => '2.44',
                'jumlah' => '17',
                'bobot' => '3',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '9',
                'name' => 'Buah-buahan',
                'volume' => '0.91',
                'jumlah' => '45',
                'bobot' => '1',
                'tgl_pengiriman' => '2023-08-01',
            ],
            [
                'id' => '10',
                'name' => 'Smartphone(s)',
                'volume' => '1.22',
                'jumlah' => '20',
                'bobot' => '0.14',
                'tgl_pengiriman' => '2023-08-01',
            ],
            [
                'id' => '11',
                'name' => 'Minuman Alkohol',
                'volume' => '0.91',
                'jumlah' => '12',
                'bobot' => '3',
                'tgl_pengiriman' => '2023-08-01',
            ],
            [
                'id' => '12',
                'name' => 'Bijih Kopi',
                'volume' => '1.13',
                'jumlah' => '23',
                'bobot' => '50',
                'tgl_pengiriman' => '2023-08-05',
            ],
            [
                'id' => '13',
                'name' => 'Motor',
                'volume' => '8.10',
                'jumlah' => '7',
                'bobot' => '149',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '14',
                'name' => 'Susu Kotak',
                'volume' => '1.53',
                'jumlah' => '21',
                'bobot' => '1',
                'tgl_pengiriman' => '2023-08-01',
            ],
            [
                'id' => '15',
                'name' => 'Laptop(s)',
                'volume' => '0.61',
                'jumlah' => '15',
                'bobot' => '3',
                'tgl_pengiriman' => '2023-08-01',
            ],
            [
                'id' => '16',
                'name' => 'TV',
                'volume' => '0.94',
                'jumlah' => '28',
                'bobot' => '9',
                'tgl_pengiriman' => '2023-08-05',
            ],
            [
                'id' => '17',
                'name' => 'Bunga',
                'volume' => '4.00',
                'jumlah' => '3',
                'bobot' => '2',
                'tgl_pengiriman' => '2023-08-04',
            ],
            [
                'id' => '18',
                'name' => 'Tangga Lipat',
                'volume' => '1.50',
                'jumlah' => '4',
                'bobot' => '2',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '19',
                'name' => 'Beton',
                'volume' => '8.14',
                'jumlah' => '7',
                'bobot' => '20',
                'tgl_pengiriman' => '2023-08-04',
            ],
            [
                'id' => '20',
                'name' => 'Buah-buahan',
                'volume' => '0.91',
                'jumlah' => '12',
                'bobot' => '1',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '21',
                'name' => 'Bata',
                'volume' => '7.12',
                'jumlah' => '10',
                'bobot' => '20',
                'tgl_pengiriman' => '2023-08-05',
            ],
            [
                'id' => '22',
                'name' => 'Sepeda',
                'volume' => '2.16',
                'jumlah' => '2',
                'bobot' => '20',
                'tgl_pengiriman' => '2023-08-04',
            ],
            [
                'id' => '23',
                'name' => 'Sofa',
                'volume' => '2.10',
                'jumlah' => '15',
                'bobot' => '66',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '24',
                'name' => 'Paku',
                'volume' => '0.06',
                'jumlah' => '89',
                'bobot' => '1',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '25',
                'name' => 'Sofa',
                'volume' => '1.93',
                'jumlah' => '15',
                'bobot' => '66',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '26',
                'name' => 'Oli',
                'volume' => '21000',
                'jumlah' => '2',
                'bobot' => '16590',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '27',
                'name' => 'LPG',
                'volume' => '22587',
                'jumlah' => '3',
                'bobot' => '11519',
                'tgl_pengiriman' => '2023-08-01',
            ],
            [
                'id' => '28',
                'name' => 'Hidrogen Peroksida',
                'volume' => '25707',
                'jumlah' => '2',
                'bobot' => '12853',
                'tgl_pengiriman' => '2023-08-05',
            ],
            [
                'id' => '29',
                'name' => 'Bensin',
                'volume' => '18537',
                'jumlah' => '3',
                'bobot' => '16030',
                'tgl_pengiriman' => '2023-08-02',
            ],
            [
                'id' => '30',
                'name' => 'Acetone',
                'volume' => '20650',
                'jumlah' => '3',
                'bobot' => '16210',
                'tgl_pengiriman' => '2023-08-04',
            ],
            [
                'id' => '31',
                'name' => 'Bensin',
                'volume' => '18537',
                'jumlah' => '2',
                'bobot' => '16030',
                'tgl_pengiriman' => '2023-08-04',
            ],
        ];
    }
}
